#spring:
  application:
    name: project1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/sbprj1
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true